version: '3.8'

services:
  endee-oss:
    build:
      context: .
      dockerfile: infra/Dockerfile
      args:
        BUILD_ARCH: avx2
        DEBUG: false
    container_name: endee-oss
    ports:
      - "8081:8080"
    ulimits:
      nofile: 100000
    environment:
      NDD_NUM_THREADS: 0
      NDD_AUTH_TOKEN: ""
    volumes:
      - endee-data:/data
    restart: unless-stopped

  vision-endee-app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: vision-endee-app
    ports:
      - "8502:8501"
    volumes:
      - ./app/data:/app/data
    depends_on:
      - endee-oss
    restart: unless-stopped

volumes:
  endee-data:
